### ISSUE TITLE
unchanged repo

### ISSUE THREAD

**Issue by mandrewmoshier** [chapman-cpsc-230/hw-0-EddieWadors#1]
I see you have not pushed any edited files back to github

**Comment by EddieWadors** [comment]
Yeah I still can't figure out how to edit my files that are on the desktop
app, but I can edit them on github and commit/pull things and put them back
into desktop. Which doesn't solve anything, but it's all I know how to do!

**Comment by mandrewmoshier** [comment]
I see you have this wokring now. We can "close" this comment now.
